version: '3.5'
services:
  db:
    image: postgres
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data
    env_file:
      - ./.zabbix.env
  
  zabbix-server:
    image: zabbix/zabbix-server-pgsql
    ports:
      - "10051:10051"
    restart: always
    depends_on:
      - "db"
    env_file:
      - ./.zabbix.env

  zabbix-web:
    image: zabbix/zabbix-web-nginx-pgsql
    ports:
      - "7000:8080"
    restart: always
    depends_on:
      - "db"
      - "zabbix-server"
    environment:
      ZBX_SERVER_HOST: zabbix-server
    env_file:
      - ./.zabbix.env
  
  zabbix-agent:
    image: zabbix/zabbix-agent
    ports:
      - "10050:10050"
    restart: always
    depends_on:
      - "db"
      - "zabbix-server"
    environment:
      ZBX_HOSTNAME: zabbix-agent
    
volumes:
  pgdata:
